apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "shopfast.fullname" . }}
  labels:
    {{- include "shopfast.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "shopfast.selectorLabels" . | nindent 6 }}
      app: {{ include "shopfast.name" . }}
